package com.test.cascade_abort;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EMCRestAPIException extends RuntimeException implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public EMCRestAPIException() {
         super();
    }

    public EMCRestAPIException(String message) {
        super(message);
    }
    
    public EMCRestAPIException(Throwable cause) {
        super(cause);
    }
    
}